### PR TITLE
Improve CHECK-LABEL error message

### PR DESCRIPTION
**Pull request by Moxinilian**
I was debugging a CHECK-LABEL related problem and struggled because I was trying to fix the wrong label in my file. This improved error message should help in those situations.

### CODE REVIEW

**Review by AntonLydike — APPROVED** [review]
Thanks a lot! :heart:

**Comment by Moxinilian** [comment]
nooo I had another change to make

**Comment by AntonLydike** [comment]
One sec

**Comment by AntonLydike** [comment]
Invited you to the repo, should be easier now!

**Pull request merged**
